[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "pyside-widgets-project"
version = "0.1.0"
description = "A PySide6 widgets application"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }

dependencies = [
    "PySide6==6.11.1",
    "curl_cffi==0.16.0",
    "python-dotenv==1.1.1",
    "google-genai==2.17.0",
    "google-api-python-client==2.198.0",
]


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]


[tool.pyside6-project]
files = [
    "widget.py",
    "form.ui",

    "cache.py",
    "config.py",

    "network/__init__.py",
    "network/request.py",

    "tools/__init__.py",
    "tools/common.py",
    "tools/gemini.py",
    "tools/leonardo.py",
]
